Corrected Enroll Button
coding-blocks/codingblocks.online pull request #91
Opened 2017-12-22 08:51 UTC by flaredragon

- Enroll button was corrected
- Buy button as it was disabled is not been shown along with preview button(Have to add razorpay component only for displaying
![screenshot from 2017-12-22 14-21-22](https://user-images.githubusercontent.com/29121452/34291693-6e656d34-e723-11e7-9be6-bb88650161e7.png)
 it)

2017-12-29 08:36 UTC, abhishek97 requested changes

2017-12-29 08:36 UTC, abhishek97 commented on app/pods/courses/preview/route.js
> +      this.get('currentUser').load().then(user => {
@flaredragon Have you tried `this.get('currentUser.user')` ? 
The user should be available via the service

2017-12-29 08:36 UTC, abhishek97 commented on app/pods/courses/preview/template.hbs
> +                  {{#if course.isFree}}
can be replaced with `{{else if}}`

2018-01-05 07:56 UTC, witty123 approved these changes

2018-01-05 12:38 UTC, abhishek97 commented
@flaredragon User is not redirected to previous path after login. This is yet to be implemented and is to be dealt in a separate PR, please remove any such logic here.

2018-01-28 13:02 UTC, closed without merging